import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import SplashCursor from "@/ui/SplashCursor";
import TargetCursor from "@/ui/TargetCursor";

const roboto = Roboto({
  subsets: ["latin"],
  preload: true,
});

export const metadata = {
  title: "HASH Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased min-h-screen flex flex-col`}
      >
        <main className="flex-grow overflow-hidden">{children}</main>
        <TargetCursor spinDuration={2} hideDefaultCursor={true} />
        {/* <SplashCursor /> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
