import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import TargetCursor from "@/ui/TargetCursor";

const roboto = Roboto({
  subsets: ["latin"],
  preload: true,
});

export const metadata = {
  title: "HASH Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased min-h-screen flex flex-col`}
      >
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
        <div className="hidden md:block">
          <TargetCursor spinDuration={2} hideDefaultCursor={true} />
        </div>
      </body>
    </html>
  );
}
